# Generated by Django 3.1.5 on 2021-01-24 23:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(max_length=16, verbose_name='Car Make')),
                ('carModel', models.CharField(max_length=16, verbose_name='Car Model')),
                ('carYear', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2021)], verbose_name='Car Model Year')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='washing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washType', models.PositiveSmallIntegerField(choices=[(1, 'Window Wash'), (2, 'Inside Wash'), (3, 'Outside Wash'), (4, 'Full Wash'), (5, 'Other type of wash')], default=5, verbose_name='Washing Type')),
                ('start', models.DateTimeField(verbose_name='Start Date/Time')),
                ('end', models.DateTimeField(verbose_name='End Date/Time')),
                ('car', models.ManyToManyField(related_name='Cars', to='wash.Car')),
            ],
        ),
        migrations.CreateModel(
            name='washingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Place Name')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Location', to='wash.location')),
                ('wash_type', models.ManyToManyField(related_name='Wash_Type', to='wash.washing')),
            ],
        ),
    ]
